---
version: "3.9"
services:
  web_server:
    build:
      context: ./flaskapp/
      args:
        buildno: 1
    container_name: flaskapp

    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - app


networks:
  app:
    driver: bridge
